artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://raw.githubusercontent.com/Durgeshsingh12712/Data-All/refs/heads/main/Unified%20Dataset/CloudWatch_Traffic_Web_Attack.csv
  local_data_file: artifacts/data_ingestion/CloudWatch_Traffic_Web_Attack.csv
  unzip_dir: artifacts/data_ingestion